# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hash',
            name='link',
        ),
        migrations.RemoveField(
            model_name='hash',
            name='user',
        ),
        migrations.AddField(
            model_name='hash',
            name='user_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
