# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0004_auto_20180513_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hash',
            name='confirmation_count',
        ),
        migrations.RemoveField(
            model_name='hash',
            name='date_confirmation',
        ),
        migrations.AddField(
            model_name='hash',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
